import 'dart:io';
import 'package:openrig_core/openrig_core.dart';
import 'package:test/test.dart';

void main() {
  final sampleRecord = QsoRecord(
    call: 'W1AW',
    band: '20m',
    mode: 'SSB',
    freqMhz: 14.225,
    timeOn: DateTime.utc(2025, 3, 15, 14, 30, 0),
    timeOff: DateTime.utc(2025, 3, 15, 14, 35, 0),
    rstSent: '59',
    rstRcvd: '57',
    name: 'Hiram',
    gridsquare: 'FN31',
    comment: 'Great signal',
  );

  group('QsoRecord.toAdif', () {
    test('serializes required fields with correct format', () {
      final adif = sampleRecord.toAdif();
      expect(adif, contains('<CALL:4>W1AW'));
      expect(adif, contains('<BAND:3>20m'));
      expect(adif, contains('<MODE:3>SSB'));
      expect(adif, contains('<FREQ:9>14.225000'));
      expect(adif, contains('<QSO_DATE:8>20250315'));
      expect(adif, contains('<TIME_ON:6>143000'));
      expect(adif, endsWith('<EOR>'));
    });

    test('serializes optional fields', () {
      final adif = sampleRecord.toAdif();
      expect(adif, contains('<RST_SENT:2>59'));
      expect(adif, contains('<RST_RCVD:2>57'));
      expect(adif, contains('<NAME:5>Hiram'));
      expect(adif, contains('<GRIDSQUARE:4>FN31'));
      expect(adif, contains('<COMMENT:12>Great signal'));
      expect(adif, contains('<TIME_OFF:6>143500'));
    });

    test('omits null optional fields', () {
      final minimal = QsoRecord(
        call: 'K1A',
        band: '40m',
        mode: 'CW',
        freqMhz: 7.025,
        timeOn: DateTime.utc(2025, 1, 1, 0, 0, 0),
      );
      final adif = minimal.toAdif();
      expect(adif, isNot(contains('<RST_SENT')));
      expect(adif, isNot(contains('<TIME_OFF')));
      expect(adif, isNot(contains('<NAME')));
    });
  });

  group('AdifLog.parse', () {
    test('round-trips a known ADIF string', () {
      final encoded = AdifLog.encode([sampleRecord]);
      final records = AdifLog.parse(encoded);

      expect(records, hasLength(1));
      final r = records.first;
      expect(r.call, equals('W1AW'));
      expect(r.band, equals('20m'));
      expect(r.mode, equals('SSB'));
      expect(r.freqMhz, closeTo(14.225, 0.001));
      expect(r.timeOn, equals(DateTime.utc(2025, 3, 15, 14, 30, 0)));
      expect(r.timeOff, equals(DateTime.utc(2025, 3, 15, 14, 35, 0)));
      expect(r.rstSent, equals('59'));
      expect(r.rstRcvd, equals('57'));
      expect(r.name, equals('Hiram'));
      expect(r.gridsquare, equals('FN31'));
      expect(r.comment, equals('Great signal'));
    });

    test('parses multiple records', () {
      final r2 = QsoRecord(
        call: 'VE3ABC',
        band: '40m',
        mode: 'FT8',
        freqMhz: 7.074,
        timeOn: DateTime.utc(2025, 3, 15, 15, 0, 0),
      );
      final encoded = AdifLog.encode([sampleRecord, r2]);
      final records = AdifLog.parse(encoded);
      expect(records, hasLength(2));
      expect(records[0].call, equals('W1AW'));
      expect(records[1].call, equals('VE3ABC'));
    });

    test('skips header before EOH', () {
      const adif = '''
Generated by SomeApp
<ADIF_VER:5>3.1.4
<EOH>
<CALL:4>W1AW<BAND:3>20m<MODE:3>SSB<FREQ:6>14.225<QSO_DATE:8>20250315<TIME_ON:6>143000<EOR>
''';
      final records = AdifLog.parse(adif);
      expect(records, hasLength(1));
      expect(records.first.call, equals('W1AW'));
    });

    test('handles ADIF without header', () {
      const adif =
          '<CALL:4>W1AW<BAND:3>20m<MODE:3>SSB<FREQ:6>14.225<QSO_DATE:8>20250315<TIME_ON:6>143000<EOR>';
      final records = AdifLog.parse(adif);
      expect(records, hasLength(1));
    });
  });

  group('AdifLog.encode', () {
    test('produces valid file with header and EOR markers', () {
      final output = AdifLog.encode([sampleRecord]);
      expect(output, contains('<ADIF_VER:5>3.1.4'));
      expect(output, contains('<PROGRAMID:7>openRig'));
      expect(output, contains('<EOH>'));
      expect(output, contains('<EOR>'));
    });
  });

  group('SOTA fields', () {
    test('round-trip through toAdif and parse', () {
      final qso = QsoRecord(
        call: 'W1AW',
        band: '20m',
        mode: 'CW',
        freqMhz: 14.060,
        timeOn: DateTime.utc(2025, 7, 1, 12, 0),
        mySotaRef: 'W7W/KG-001',
        sotaRef: 'VE2/LR-001',
      );
      final encoded = AdifLog.encode([qso]);
      final parsed = AdifLog.parse(encoded);
      expect(parsed, hasLength(1));
      expect(parsed[0].mySotaRef, equals('W7W/KG-001'));
      expect(parsed[0].sotaRef, equals('VE2/LR-001'));
    });
  });

  group('POTA fields', () {
    test('round-trip through toAdif and parse', () {
      final qso = QsoRecord(
        call: 'K1ABC',
        band: '40m',
        mode: 'SSB',
        freqMhz: 7.200,
        timeOn: DateTime.utc(2025, 7, 1, 13, 0),
        myPotaRef: 'K-0001',
        potaRef: 'K-4566',
      );
      final encoded = AdifLog.encode([qso]);
      final parsed = AdifLog.parse(encoded);
      expect(parsed, hasLength(1));
      expect(parsed[0].myPotaRef, equals('K-0001'));
      expect(parsed[0].potaRef, equals('K-4566'));
    });

    test('multiple parks round-trip (comma-separated)', () {
      final qso = QsoRecord(
        call: 'N5XYZ',
        band: '20m',
        mode: 'FT8',
        freqMhz: 14.074,
        timeOn: DateTime.utc(2025, 7, 2, 14, 0),
        potaRef: 'K-0001,K-0002',
      );
      final adif = qso.toAdif();
      expect(adif, contains('<POTA_REF:13>K-0001,K-0002'));
      final parsed = AdifLog.parse(AdifLog.encode([qso]));
      expect(parsed[0].potaRef, equals('K-0001,K-0002'));
    });
  });

  group('SOTA/POTA absent when null', () {
    test('fields not emitted when null', () {
      final qso = QsoRecord(
        call: 'W1AW',
        band: '20m',
        mode: 'SSB',
        freqMhz: 14.225,
        timeOn: DateTime.utc(2025, 7, 1, 12, 0),
      );
      final adif = qso.toAdif();
      expect(adif, isNot(contains('MY_SOTA_REF')));
      expect(adif, isNot(contains('SOTA_REF')));
      expect(adif, isNot(contains('MY_POTA_REF')));
      expect(adif, isNot(contains('POTA_REF')));
    });
  });

  group('AdifLog.appendRecord', () {
    test('creates a new file when none exists', () async {
      final tmpDir = await Directory.systemTemp.createTemp('adif_test_');
      final path = '${tmpDir.path}/new_log.adi';

      try {
        await AdifLog.appendRecord(path, sampleRecord);

        final file = File(path);
        expect(await file.exists(), isTrue);

        final content = await file.readAsString();
        expect(content, contains('<EOH>'));
        expect(content, contains('<CALL:4>W1AW'));
        expect(content, contains('<EOR>'));
      } finally {
        await tmpDir.delete(recursive: true);
      }
    });

    test('appends to an existing file', () async {
      final tmpDir = await Directory.systemTemp.createTemp('adif_test_');
      final path = '${tmpDir.path}/append_log.adi';

      try {
        // Create initial file
        await AdifLog.appendRecord(path, sampleRecord);

        // Append a second record
        final r2 = QsoRecord(
          call: 'VE3ABC',
          band: '40m',
          mode: 'CW',
          freqMhz: 7.025,
          timeOn: DateTime.utc(2025, 6, 1, 12, 0, 0),
        );
        await AdifLog.appendRecord(path, r2);

        final content = await File(path).readAsString();
        // Should have both records
        final records = AdifLog.parse(content);
        expect(records, hasLength(2));
        expect(records[0].call, equals('W1AW'));
        expect(records[1].call, equals('VE3ABC'));
      } finally {
        await tmpDir.delete(recursive: true);
      }
    });
  });
}
